# Generated by Django 4.2.6 on 2023-11-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tele', '0004_images_post_delete_image_images_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kartochka',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='kartochka',
            name='year',
        ),
        migrations.RemoveField(
            model_name='list_uchastkov',
            name='uchastok',
        ),
        migrations.RemoveField(
            model_name='uchastok',
            name='okrug',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='msg',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='media/img', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='images',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tele.article'),
        ),
        migrations.DeleteModel(
            name='bith_year',
        ),
        migrations.DeleteModel(
            name='kartochka',
        ),
        migrations.DeleteModel(
            name='list_Uchastkov',
        ),
        migrations.DeleteModel(
            name='Okrug',
        ),
        migrations.DeleteModel(
            name='Uchastok',
        ),
    ]
